import type { Category, ChatMessage, Order, Product, Reel, SellerProfile, ShopStory, User } from "./types";

const CATALOG_IMAGE =
  "https://avatars.mds.yandex.net/i?id=1e8774bc3c8dfea35d793d6b63b880c5f589c7cc-10385933-images-thumbs&n=13";

const img = (_id?: string) => CATALOG_IMAGE;

export const categoryGroups = [
  "Мода",
  "Техника",
  "Дом",
  "Красота",
  "Дети и животные",
  "Спорт и хобби",
  "Продукты",
] as const;

export const categories: Category[] = [
  { slug: "odezhda", name: "Одежда", icon: "👗", group: "Мода" },
  { slug: "obuv", name: "Обувь", icon: "👟", group: "Мода" },
  { slug: "aksessuary", name: "Аксессуары", icon: "👜", group: "Мода" },
  { slug: "ukrasheniya", name: "Украшения", icon: "💍", group: "Мода" },
  { slug: "elektronika", name: "Электроника", icon: "📱", group: "Техника" },
  { slug: "bytovaya", name: "Бытовая техника", icon: "🔌", group: "Техника" },
  { slug: "kompjutery", name: "Компьютеры", icon: "💻", group: "Техника" },
  { slug: "igry", name: "Игры", icon: "🎮", group: "Техника" },
  { slug: "dom", name: "Дом", icon: "🏠", group: "Дом" },
  { slug: "mebel", name: "Мебель", icon: "🛋️", group: "Дом" },
  { slug: "kuhnya", name: "Кухня", icon: "🍳", group: "Дом" },
  { slug: "sad", name: "Сад и дача", icon: "🌿", group: "Дом" },
  { slug: "remont", name: "Ремонт", icon: "🔧", group: "Дом" },
  { slug: "krasota", name: "Красота", icon: "✨", group: "Красота" },
  { slug: "zdorovie", name: "Здоровье", icon: "💊", group: "Красота" },
  { slug: "detiam", name: "Детям", icon: "🧸", group: "Дети и животные" },
  { slug: "zootovary", name: "Зоотовары", icon: "🐾", group: "Дети и животные" },
  { slug: "sport", name: "Спорт", icon: "🏃", group: "Спорт и хобби" },
  { slug: "hobbi", name: "Хобби", icon: "🎨", group: "Спорт и хобби" },
  { slug: "knigi", name: "Книги", icon: "📚", group: "Спорт и хобби" },
  { slug: "kantselyariya", name: "Канцтовары", icon: "✏️", group: "Спорт и хобби" },
  { slug: "produkty", name: "Продукты", icon: "🛒", group: "Продукты" },
];

export const products: Product[] = [
  {
    id: "yandex-station-mini",
    title: "Умная колонка Яндекс Станция Мини 2",
    description:
      "Компактная колонка с Алисой, объёмным звуком и управлением умным домом. Подходит для кухни и спальни.",
    price: 4990,
    oldPrice: 7990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "elektronika",
    image: img("photo-1608043152269-423dbba4e7e1"),
    images: [img("photo-1608043152269-423dbba4e7e1"), img("photo-1543512214-318c7553f230")],
    sellerId: "shop-tech",
    sellerName: "Зона Техники",
    city: "Москва",
    weightKg: 0.6,
    inStock: 214,
    delivery: ["cdek", "pochta"],
    tags: ["хит", "алиса"],
  },
  {
    id: "nike-air-max",
    title: "Кроссовки Nike Air Max Pulse",
    description: "Легкая сетка, амортизация Air и повседневный силуэт. Размеры 36–46.",
    price: 8990,
    oldPrice: 12990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "obuv",
    image: img("photo-1542291026-7eec264c27ff"),
    images: [img("photo-1542291026-7eec264c27ff"), img("photo-1460353581641-37baddab0fa2")],
    sellerId: "shop-tech",
    sellerName: "Норд Спорт",
    city: "Москва",
    weightKg: 0.9,
    inStock: 88,
    delivery: ["cdek", "pochta"],
    tags: ["спорт"],
  },
  {
    id: "sony-wh1000",
    title: "Наушники Sony WH-1000XM5",
    description: "Флагманское шумоподавление, 30 часов работы и прозрачный микрофон для звонков.",
    price: 24990,
    oldPrice: 32990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "elektronika",
    image: img("photo-1505740420928-5e560c06d30e"),
    images: [img("photo-1505740420928-5e560c06d30e")],
    sellerId: "shop-tech",
    sellerName: "Зона Техники",
    city: "Санкт-Петербург",
    weightKg: 0.4,
    inStock: 41,
    delivery: ["cdek", "pochta"],
    tags: ["хит"],
  },
  {
    id: "summer-dress",
    title: "Платье летнее миди в цветочек",
    description: "Лёгкий штапель, свободный крой, подойдёт для города и отпуска.",
    price: 2490,
    oldPrice: 3990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "odezhda",
    image: img("photo-1515372039744-b8f02a3ae446"),
    images: [img("photo-1515372039744-b8f02a3ae446")],
    sellerId: "shop-atelier",
    sellerName: "Atelier South",
    city: "Краснодар",
    weightKg: 0.3,
    inStock: 60,
    delivery: ["cdek", "pochta"],
    tags: ["лето"],
  },
  {
    id: "delonghi-coffee",
    title: "Кофемашина De'Longhi Magnifica",
    description: "Зерновой автомат: капучино, эспрессо и регулировка помола.",
    price: 18990,
    oldPrice: 24990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "bytovaya",
    image: img("photo-1495474472287-4d71bcdd2085"),
    images: [img("photo-1495474472287-4d71bcdd2085")],
    sellerId: "shop-home",
    sellerName: "Дом и уют",
    city: "Москва",
    weightKg: 9.2,
    inStock: 19,
    delivery: ["cdek"],
    tags: ["кухня"],
  },
  {
    id: "city-backpack",
    title: "Рюкзак городской 20 л, защита ноутбука",
    description: "Отделение 15.6\", водоотталкивающая ткань, скрытый карман.",
    price: 3290,
    oldPrice: 4590,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "aksessuary",
    image: img("photo-1553062407-98eeb64c6a62"),
    images: [img("photo-1553062407-98eeb64c6a62")],
    sellerId: "shop-atelier",
    sellerName: "Atelier South",
    city: "Казань",
    weightKg: 0.7,
    inStock: 120,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "smart-watch-pro",
    title: "Умные часы Watch Pro GPS",
    description: "Пульс, сон, NFC-оплата и 7 дней без зарядки.",
    price: 12990,
    oldPrice: 16990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "elektronika",
    image: img("photo-1434493789847-2f02dc6ca35d"),
    images: [img("photo-1434493789847-2f02dc6ca35d")],
    sellerId: "shop-tech",
    sellerName: "Зона Техники",
    city: "Москва",
    weightKg: 0.2,
    inStock: 73,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "perfume-bloom",
    title: "Парфюмерная вода Bloom 50 мл",
    description: "Цветочно-древесный аромат: пион, мускус и бергамот.",
    price: 4590,
    oldPrice: 6200,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "krasota",
    image: img("photo-1541643600914-78b084366893"),
    images: [img("photo-1541643600914-78b084366893")],
    sellerId: "shop-bloom",
    sellerName: "Maison Bloom",
    city: "Москва",
    weightKg: 0.25,
    inStock: 45,
    delivery: ["cdek", "pochta"],
    tags: ["хит"],
  },
  {
    id: "robot-vacuum",
    title: "Робот-пылесос с влажной уборкой",
    description: "Лидар, карта квартиры и станция самоочистки. Работает с Алисой.",
    price: 15990,
    oldPrice: 22990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "bytovaya",
    image: img("photo-1558317374-058bbf0b0d36"),
    images: [img("photo-1558317374-058bbf0b0d36")],
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    city: "Москва",
    weightKg: 4.1,
    inStock: 33,
    delivery: ["cdek", "pochta"],
    tags: ["хорошая цена"],
  },
  {
    id: "monitor-27",
    title: "Монитор 27\" QHD 165 Гц IPS",
    description: "Для работы и игр: тонкие рамки, HDR400, USB-C 65 Вт.",
    price: 18990,
    oldPrice: 24990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "kompjutery",
    image: img("photo-1527443224154-c4a3942d3acf"),
    images: [img("photo-1527443224154-c4a3942d3acf")],
    sellerId: "shop-signal",
    sellerName: "Сигнал",
    city: "Санкт-Петербург",
    weightKg: 5.5,
    inStock: 27,
    delivery: ["cdek"],
    tags: [],
  },
  {
    id: "mech-keyboard",
    title: "Клавиатура механическая TKL, свитчи красные",
    description: "Горячая замена, RGB и кейкапы PBT. Раскладка RU/EN.",
    price: 5490,
    oldPrice: 7990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "kompjutery",
    image: img("photo-1511467687858-23d96c32e4ae"),
    images: [img("photo-1511467687858-23d96c32e4ae")],
    sellerId: "shop-signal",
    sellerName: "Сигнал",
    city: "Москва",
    weightKg: 0.85,
    inStock: 54,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "desk-lamp",
    title: "Лампа настольная LED с беспроводной зарядкой",
    description: "3 цветовые температуры, диммер и Qi 15 Вт на основании.",
    price: 1890,
    oldPrice: 2490,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "dom",
    image: img("photo-1507473882602-a897dfd0ad8d"),
    images: [img("photo-1507473882602-a897dfd0ad8d")],
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    city: "Казань",
    weightKg: 1.1,
    inStock: 140,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "winter-jacket",
    title: "Куртка зимняя пуховая, −25 °C",
    description: "Натуральный пух 90/10, капюшон с мехом, карманы на молнии.",
    price: 7990,
    oldPrice: 11990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "odezhda",
    image: img("photo-1591047139829-d91aecb6caea"),
    images: [img("photo-1591047139829-d91aecb6caea")],
    sellerId: "shop-nord",
    sellerName: "Nord Wear",
    city: "Новосибирск",
    weightKg: 1.4,
    inStock: 38,
    delivery: ["cdek", "pochta"],
    tags: ["зима"],
  },
  {
    id: "mountain-bike",
    title: "Велосипед горный 29\", 21 скорость",
    description: "Алюминиевая рама, дисковые тормоза, вилка с ходом 100 мм.",
    price: 24990,
    oldPrice: 32990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "sport",
    image: img("photo-1485965120184-e220f721d03e"),
    images: [img("photo-1485965120184-e220f721d03e")],
    sellerId: "shop-ride",
    sellerName: "Ride Club",
    city: "Екатеринбург",
    weightKg: 14.5,
    inStock: 11,
    delivery: ["cdek"],
    tags: [],
  },
  {
    id: "sony-camera",
    title: "Фотоаппарат Sony ZV-E10 kit 16-50",
    description: "Для блогеров: поворотный экран, автофокус по глазам и чистый звук.",
    price: 45990,
    oldPrice: 52990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "elektronika",
    image: img("photo-1516035069371-29a1b244cc32"),
    images: [img("photo-1516035069371-29a1b244cc32")],
    sellerId: "shop-signal",
    sellerName: "Сигнал",
    city: "Москва",
    weightKg: 1.2,
    inStock: 8,
    delivery: ["cdek"],
    tags: ["reels"],
  },
  {
    id: "cookware-set",
    title: "Набор посуды 8 предметов, антипригар",
    description: "Ковши, сковороды и кастрюли с крышками. Индукция.",
    price: 3990,
    oldPrice: 5990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "kuhnya",
    image: img("photo-1556911220-bff31c812dba"),
    images: [img("photo-1556911220-bff31c812dba")],
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    city: "Краснодар",
    weightKg: 6.8,
    inStock: 22,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "iphone-13-used",
    title: "iPhone 13 128 ГБ, отличное состояние",
    description: "Батарея 87%, комплект: коробка и кабель. Без сколов, стёкла родные.",
    price: 32990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "private",
    condition: "used",
    category: "elektronika",
    image: img("photo-1511707171634-5f897ff02aa9"),
    images: [img("photo-1511707171634-5f897ff02aa9")],
    sellerId: "private-ivan",
    sellerName: "Иван, частное лицо",
    city: "Москва",
    weightKg: 0.3,
    inStock: 1,
    delivery: ["pickup", "cdek"],
    tags: ["б/у"],
  },
  {
    id: "corner-sofa-used",
    title: "Диван угловой, велюр, торг",
    description: "3 года, без пятен. Самовывоз, помогу погрузить.",
    price: 18900,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "private",
    condition: "used",
    category: "mebel",
    image: img("photo-1555041469-a586c61ea9bc"),
    images: [img("photo-1555041469-a586c61ea9bc")],
    sellerId: "private-olga",
    sellerName: "Ольга",
    city: "Санкт-Петербург",
    weightKg: 55,
    inStock: 1,
    delivery: ["pickup"],
    tags: ["б/у"],
  },
  {
    id: "bike-used",
    title: "Велосипед городской б/у, 28\"",
    description: "Крылья, багажник, свет. Цепь новая. Отдам с насосом.",
    price: 8500,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "private",
    condition: "used",
    category: "sport",
    image: img("photo-1571068316344-75bc76f77890"),
    images: [img("photo-1571068316344-75bc76f77890")],
    sellerId: "private-kirill",
    sellerName: "Кирилл",
    city: "Казань",
    weightKg: 13,
    inStock: 1,
    delivery: ["pickup", "cdek"],
    tags: ["б/у"],
  },
  {
    id: "guitar-used",
    title: "Гитара акустическая Yamaha F310",
    description: "Струны свежие, чехол в комплекте. Царапина у грифа — на звук не влияет.",
    price: 6200,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "private",
    condition: "used",
    category: "hobbi",
    image: img("photo-1510915361894-db8b60106cb1"),
    images: [img("photo-1510915361894-db8b60106cb1")],
    sellerId: "private-dasha",
    sellerName: "Дарья",
    city: "Москва",
    weightKg: 2.4,
    inStock: 1,
    delivery: ["pickup", "pochta"],
    tags: ["б/у"],
  },
  {
    id: "macbook-air-m1",
    title: "MacBook Air M1 8/256, 2020 б/у",
    description: "Циклов 218, батарея 91%. В комплекте зарядка. Без вмятин.",
    price: 45900,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "private",
    condition: "used",
    category: "kompjutery",
    image: img("photo-1517336714731-489689fd1ca8"),
    images: [img("photo-1517336714731-489689fd1ca8")],
    sellerId: "private-gleb",
    sellerName: "Глеб",
    city: "Новосибирск",
    weightKg: 1.3,
    inStock: 1,
    delivery: ["pickup", "cdek"],
    tags: ["б/у"],
  },
  {
    id: "fridge-used",
    title: "Холодильник двухкамерный, рабочий",
    description: "No Frost, 320 л. Самовывоз с 1 этажа. Проверен мастером.",
    price: 12000,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "private",
    condition: "used",
    category: "bytovaya",
    image: img("photo-1571175443880-49e1d25b6ee5"),
    images: [img("photo-1571175443880-49e1d25b6ee5")],
    sellerId: "private-tanya",
    sellerName: "Татьяна",
    city: "Екатеринбург",
    weightKg: 62,
    inStock: 1,
    delivery: ["pickup"],
    tags: ["б/у"],
  },
  {
    id: "handmade-candles",
    title: "Свечи соевые ручной работы, набор 3 шт",
    description: "Ароматы: ваниль, сандал, бергамот. Горят по 40 часов. От магазина на WOAson.",
    price: 890,
    oldPrice: 1290,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "dom",
    image: img("photo-1603006905004-abe27117f6b8"),
    images: [img("photo-1603006905004-abe27117f6b8")],
    sellerId: "seller-demo",
    sellerName: "Лавка Магасова",
    city: "Москва",
    weightKg: 0.6,
    inStock: 40,
    delivery: ["cdek", "pochta"],
    tags: ["своё"],
    tradeType: "retail",
  },
  {
    id: "phone-case-woa",
    title: "Чехол для смартфона WOAson MagSafe",
    description: "Силикон с микрофиброй, защита камеры, совместим с беспроводной зарядкой.",
    price: 490,
    oldPrice: 790,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "elektronika",
    image: img("photo-1601784551446-20c9e07cdbdb"),
    images: [img("photo-1601784551446-20c9e07cdbdb")],
    sellerId: "seller-demo",
    sellerName: "Лавка Магасова",
    city: "Москва",
    weightKg: 0.08,
    inStock: 200,
    delivery: ["cdek", "pochta"],
    tags: ["своё"],
    tradeType: "retail",
  },
  {
    id: "kids-constructor",
    title: "Конструктор деревянный, 80 деталей",
    description: "Экологичный бук, с 3 лет. Развивает моторику, без острых углов.",
    price: 1590,
    oldPrice: 2190,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "detiam",
    image: img("photo-1515488042361-ee00e0ddd4e4"),
    images: [img("photo-1515488042361-ee00e0ddd4e4")],
    sellerId: "shop-kids",
    sellerName: "Детский угол",
    city: "Москва",
    weightKg: 1.1,
    inStock: 70,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "sunglasses",
    title: "Очки солнцезащитные UV400",
    description: "Поляризация, лёгкая оправа. Кейс в комплекте.",
    price: 1290,
    oldPrice: 1990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "aksessuary",
    image: img("photo-1572635196237-14b3f281503f"),
    images: [img("photo-1572635196237-14b3f281503f")],
    sellerId: "shop-nord",
    sellerName: "Nord Wear",
    city: "Москва",
    weightKg: 0.15,
    inStock: 95,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "chelsea-boots",
    title: "Челси кожаные, чёрные",
    description: "Натуральная кожа, резиновая подошва, размерная сетка 36–45.",
    price: 5490,
    oldPrice: 7990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "obuv",
    image: img("photo-1549298916-b41d501d3772"),
    images: [img("photo-1549298916-b41d501d3772")],
    sellerId: "shop-nord",
    sellerName: "Nord Wear",
    city: "Москва",
    weightKg: 0.9,
    inStock: 52,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "leather-belt",
    title: "Ремень кожаный, пряжка матовая",
    description: "Итальянская кожа, ширина 3.5 см. Подарочная коробка.",
    price: 1890,
    oldPrice: 2590,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "aksessuary",
    image: img("photo-1624222247344-550fb60583c2"),
    images: [img("photo-1624222247344-550fb60583c2")],
    sellerId: "shop-atelier",
    sellerName: "Atelier South",
    city: "Краснодар",
    weightKg: 0.2,
    inStock: 80,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "silver-ring",
    title: "Кольцо серебро 925, минимализм",
    description: "Родированное покрытие, размеры 15–20. Сертификат пробы.",
    price: 3290,
    oldPrice: 4590,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "ukrasheniya",
    image: img("photo-1515562143877-fd2c037b5d4e"),
    images: [img("photo-1515562143877-fd2c037b5d4e")],
    sellerId: "shop-bloom",
    sellerName: "Maison Bloom",
    city: "Москва",
    weightKg: 0.05,
    inStock: 36,
    delivery: ["cdek", "pochta"],
    tags: ["хит"],
  },
  {
    id: "gamepad-pro",
    title: "Геймпад беспроводной, PC / консоль",
    description: "Холлы на стиках, вибрация, 20 часов на одном заряде.",
    price: 3990,
    oldPrice: 5490,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "igry",
    image: img("photo-1606144042614-b2417e99c4e3"),
    images: [img("photo-1606144042614-b2417e99c4e3")],
    sellerId: "shop-tech",
    sellerName: "Зона Техники",
    city: "Москва",
    weightKg: 0.35,
    inStock: 64,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "oak-table",
    title: "Стол обеденный дуб, 160×80",
    description: "Массив дуба, масло, ножки-трапеция. Собирается за 20 минут.",
    price: 18990,
    oldPrice: 24990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "mebel",
    image: img("photo-1533090481720-856c6e3c1fdc"),
    images: [img("photo-1533090481720-856c6e3c1fdc")],
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    city: "Москва",
    weightKg: 28,
    inStock: 7,
    delivery: ["cdek"],
    tags: [],
  },
  {
    id: "garden-shears",
    title: "Секатор садовый, срез до 24 мм",
    description: "Сталь SK5, храповый механизм, рукоять с фиксатором.",
    price: 890,
    oldPrice: 1290,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "sad",
    image: img("photo-1416879595882-3373a0480b5b"),
    images: [img("photo-1416879595882-3373a0480b5b")],
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    city: "Казань",
    weightKg: 0.4,
    inStock: 110,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "cordless-drill",
    title: "Дрель-шуруповёрт 18 В, 2 аккумулятора",
    description: "50 Н·м, LED, кейс и биты в комплекте. Для дома и дачи.",
    price: 4490,
    oldPrice: 6990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "remont",
    image: img("photo-1504148455328-c376907d081c"),
    images: [img("photo-1504148455328-c376907d081c")],
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    city: "Екатеринбург",
    weightKg: 2.1,
    inStock: 29,
    delivery: ["cdek", "pochta"],
    tags: ["хорошая цена"],
  },
  {
    id: "vitamins-d3",
    title: "Витамин D3 2000 МЕ, 90 капсул",
    description: "На масле, без красителей. Сертификат качества в карточке.",
    price: 690,
    oldPrice: 990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "zdorovie",
    image: img("photo-1584308666744-24d5c474f2ae"),
    images: [img("photo-1584308666744-24d5c474f2ae")],
    sellerId: "shop-bloom",
    sellerName: "Maison Bloom",
    city: "Москва",
    weightKg: 0.12,
    inStock: 200,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "cat-tower",
    title: "Когтеточка-домик, 120 см",
    description: "Сизаль, плюш, площадка сверху. Выдерживает кота до 8 кг.",
    price: 2490,
    oldPrice: 3490,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "zootovary",
    image: img("photo-1514888286974-6c03e2ca1dba"),
    images: [img("photo-1514888286974-6c03e2ca1dba")],
    sellerId: "shop-kids",
    sellerName: "Детский угол",
    city: "Москва",
    weightKg: 6.5,
    inStock: 18,
    delivery: ["cdek"],
    tags: [],
  },
  {
    id: "design-book",
    title: "Книга «Как устроен предмет»",
    description: "240 страниц, твёрдая обложка. Про форму, материал и быт.",
    price: 1490,
    oldPrice: 1990,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "knigi",
    image: img("photo-1512820790803-83ca734da794"),
    images: [img("photo-1512820790803-83ca734da794")],
    sellerId: "seller-demo",
    sellerName: "Лавка Магасова",
    city: "Москва",
    weightKg: 0.7,
    inStock: 44,
    delivery: ["cdek", "pochta"],
    tags: ["своё"],
    tradeType: "retail",
  },
  {
    id: "notebook-set",
    title: "Набор тетрадей в точку, 3 шт",
    description: "A5, 80 г/м², нумерация страниц. Для работы и учёбы.",
    price: 590,
    oldPrice: 890,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "kantselyariya",
    image: img("photo-1455390582262-044cdead277a"),
    images: [img("photo-1455390582262-044cdead277a")],
    sellerId: "shop-signal",
    sellerName: "Сигнал",
    city: "Москва",
    weightKg: 0.45,
    inStock: 160,
    delivery: ["cdek", "pochta"],
    tags: [],
  },
  {
    id: "honey-set",
    title: "Мёд цветочный, набор 3 банки × 250 г",
    description: "Алтай, без нагрева. Липа, гречиха, разнотравье.",
    price: 1290,
    oldPrice: 1790,
    rating: 0,
    reviewsCount: 0,
    reviews: [],
    sellerKind: "shop",
    condition: "new",
    category: "produkty",
    image: img("photo-1587049352846-4a222e784d38"),
    images: [img("photo-1587049352846-4a222e784d38")],
    sellerId: "seller-demo",
    sellerName: "Лавка Магасова",
    city: "Москва",
    weightKg: 1.0,
    inStock: 55,
    delivery: ["cdek", "pochta"],
    tags: ["своё"],
    tradeType: "retail",
  },
];

export const reels: Reel[] = [
  {
    id: "reel-station",
    productId: "yandex-station-mini",
    sellerId: "shop-tech",
    sellerName: "Зона Техники",
    title: "Распаковка Яндекс Станции Мини",
    caption: "Алиса, свет и утренние новости за 40 секунд.",
    likes: 12840,
    comments: [
      { id: "c1", author: "Ника", text: "Уже в корзине 🔥", createdAt: "10.08.2026" },
      { id: "c2", author: "Борис", text: "Цвет графит лучше белого", createdAt: "11.08.2026" },
    ],
    durationSec: 24,
    gradient: ["#1c1917", "#e2571b"],
  },
  {
    id: "reel-nike",
    productId: "nike-air-max",
    sellerId: "shop-tech",
    sellerName: "Норд Спорт",
    title: "Air Max на улицах Москвы",
    caption: "Как сидят, как пружинят, с чем носить летом.",
    likes: 9021,
    comments: [{ id: "c3", author: "Тимур", text: "Беру 43", createdAt: "12.08.2026" }],
    durationSec: 18,
    gradient: ["#111827", "#f97316"],
  },
  {
    id: "reel-iphone",
    productId: "iphone-13-used",
    sellerId: "private-ivan",
    sellerName: "Иван",
    title: "iPhone 13 с проверкой — честный осмотр",
    caption: "Батарея, экраны, Face ID. Без скрытых нюансов.",
    likes: 4302,
    comments: [{ id: "c4", author: "Лера", text: "Встреча у метро — удобно", createdAt: "09.08.2026" }],
    durationSec: 32,
    gradient: ["#0f172a", "#38bdf8"],
  },
  {
    id: "reel-jacket",
    productId: "winter-jacket",
    sellerId: "shop-nord",
    sellerName: "Nord Wear",
    title: "Пуховик −25: тест на ветру",
    caption: "Капюшон, швы и как не выглядеть как одеяло.",
    likes: 6710,
    comments: [{ id: "c5", author: "Соня", text: "Цвет графит 💔", createdAt: "08.08.2026" }],
    durationSec: 21,
    gradient: ["#292524", "#e2571b"],
  },
  {
    id: "reel-vacuum",
    productId: "robot-vacuum",
    sellerId: "shop-dom",
    sellerName: "ДомМаркет",
    title: "Робот против шерсти за 60 секунд",
    caption: "Карта квартиры, станция и реальный шум.",
    likes: 5120,
    comments: [{ id: "c6", author: "Кот Барсик", text: "Не одобряю", createdAt: "07.08.2026" }],
    durationSec: 28,
    gradient: ["#134e4a", "#22d3ee"],
  },
  {
    id: "reel-perfume",
    productId: "perfume-bloom",
    sellerId: "shop-bloom",
    sellerName: "Maison Bloom",
    title: "Bloom: как пахнет вживую",
    caption: "Пион, мускус и стойкость до вечера.",
    likes: 8804,
    comments: [{ id: "c7", author: "Мила", text: "Шлейф божественный", createdAt: "13.08.2026" }],
    durationSec: 16,
    gradient: ["#4c0519", "#fb7185"],
  },
  {
    id: "reel-candles",
    productId: "handmade-candles",
    sellerId: "seller-demo",
    sellerName: "Лавка Магасова",
    title: "Как мы заливаем свечи",
    caption: "Соевый воск, три аромата, подарочная коробка.",
    likes: 1560,
    comments: [{ id: "c9", author: "Полина", text: "Хочу набор ваниль", createdAt: "14.08.2026" }],
    durationSec: 22,
    gradient: ["#3f2a14", "#e8b86d"],
  },
];

export const shops: SellerProfile[] = [
  {
    id: "shop-tech",
    shopName: "Зона Техники",
    description:
      "Гаджеты, звук и умный дом. Проверяем каждую партию, отправляем СДЭКом в день заказа.",
    logo: "📡",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    phone: "+7 495 100-20-30",
    kind: "shop",
  },
  {
    id: "shop-atelier",
    shopName: "Atelier South",
    description: "Летние платья и городские сумки с юга. Свои лекала, небольшие партии.",
    logo: "✂️",
    city: "Краснодар",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-home",
    shopName: "Дом и уют",
    description: "Кофемашины, свет и мелочи для кухни. Помогаем подобрать под площадь квартиры.",
    logo: "🫖",
    city: "Москва",
    delivery: ["cdek"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-bloom",
    shopName: "Maison Bloom",
    description: "Парфюмерия и уход. Оригиналы, пробники и подбор по нотам.",
    logo: "🌸",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-dom",
    shopName: "ДомМаркет",
    description: "Техника для дома и уборки. Роботы, станции, расходники в наличии.",
    logo: "🛋️",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-signal",
    shopName: "Сигнал",
    description: "Мониторы, клавиатуры и свет для рабочего места.",
    logo: "🖥️",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-nord",
    shopName: "Nord Wear",
    description: "Верхняя одежда и аксессуары к холоду. Тест на ветру — в Шортс.",
    logo: "🧥",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-ride",
    shopName: "Ride Club",
    description: "Велосипеды и экипировка. Сборка, настройка, самовывоз.",
    logo: "🚲",
    city: "Москва",
    delivery: ["cdek", "pickup"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "shop-kids",
    shopName: "Детский угол",
    description: "Игрушки из дерева и текстиля. Без острых углов, с 3 лет.",
    logo: "🧸",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    kind: "shop",
  },
  {
    id: "private-ivan",
    shopName: "Иван",
    description: "Продаю проверенную технику с осмотром. Встреча в городе или отправка.",
    logo: "👤",
    city: "Москва",
    delivery: ["pickup", "cdek"],
    banner: CATALOG_IMAGE,
    kind: "private",
  },
  {
    id: "private-olga",
    shopName: "Ольга",
    description: "Мебель и вещи для дома с бережной эксплуатацией.",
    logo: "👤",
    city: "Москва",
    delivery: ["pickup"],
    banner: CATALOG_IMAGE,
    kind: "private",
  },
  {
    id: "private-kirill",
    shopName: "Кирилл",
    description: "Музыкальные инструменты и свет. Можно проверить до сделки.",
    logo: "🎸",
    city: "Санкт-Петербург",
    delivery: ["pickup", "cdek"],
    banner: CATALOG_IMAGE,
    kind: "private",
  },
  {
    id: "private-dasha",
    shopName: "Дарья",
    description: "Вело и спорт. Отдам с комплектом, фото по запросу в чате.",
    logo: "👤",
    city: "Казань",
    delivery: ["pickup"],
    banner: CATALOG_IMAGE,
    kind: "private",
  },
  {
    id: "private-gleb",
    shopName: "Глеб",
    description: "Ноутбуки и рабочие станции. Диагностика перед продажей.",
    logo: "💻",
    city: "Новосибирск",
    delivery: ["cdek", "pickup"],
    banner: CATALOG_IMAGE,
    kind: "private",
  },
  {
    id: "private-tanya",
    shopName: "Татьяна",
    description: "Спорттовары б/у в хорошем состоянии. Самовывоз.",
    logo: "🏃",
    city: "Екатеринбург",
    delivery: ["pickup"],
    banner: CATALOG_IMAGE,
    kind: "private",
  },
  {
    id: "seller-demo",
    shopName: "Лавка Магасова",
    description: "Свечи, аксессуары и вещи, которые хочется дарить. Своё производство, розница и опт.",
    logo: "🕯️",
    city: "Москва",
    delivery: ["cdek", "pochta"],
    banner: CATALOG_IMAGE,
    phone: "+7 900 444-55-66",
    kind: "shop",
  },
];

const story = (id: string, sellerId: string, caption: string): ShopStory => ({
  id,
  sellerId,
  image: CATALOG_IMAGE,
  caption,
  createdAt: "16.08.2026",
});

export const stories: ShopStory[] = [
  story("st-tech-1", "shop-tech", "Новая партия станций — распаковка сегодня"),
  story("st-tech-2", "shop-tech", "Наушники в наличии, цвет чёрный"),
  story("st-nord-1", "shop-nord", "Пуховик −25: тест на крыше"),
  story("st-bloom-1", "shop-bloom", "Bloom: как пахнет вживую"),
  story("st-demo-1", "seller-demo", "Заливка свечей — ваниль и сандал"),
  story("st-demo-2", "seller-demo", "Чехлы MagSafe прибыли на склад"),
  story("st-ivan-1", "private-ivan", "iPhone 13: батарея 87%, осмотр у метро"),
  story("st-dom-1", "shop-dom", "Робот против шерсти за минуту"),
];

export const seedOrders: Order[] = [
  {
    id: "WOA-88021",
    createdAt: "2026-08-16T08:12:00.000Z",
    buyerId: "buyer-demo",
    sellerId: "seller-demo",
    items: [
      {
        productId: "handmade-candles",
        title: "Свечи соевые ручной работы, набор 3 шт",
        price: 890,
        qty: 2,
        image: CATALOG_IMAGE,
      },
    ],
    city: "Москва",
    address: "ул. Арбат, 12",
    delivery: "cdek",
    deliveryPrice: 350,
    eta: "1–2 дня",
    status: "placed",
    total: 2130,
  },
  {
    id: "WOA-87910",
    createdAt: "2026-08-15T14:40:00.000Z",
    buyerId: "buyer-demo",
    sellerId: "seller-demo",
    items: [
      {
        productId: "phone-case-woa",
        title: "Чехол для смартфона WOAson MagSafe",
        price: 490,
        qty: 3,
        image: CATALOG_IMAGE,
      },
    ],
    city: "Казань",
    address: "ул. Баумана, 5",
    delivery: "pochta",
    deliveryPrice: 280,
    eta: "3–5 дней",
    trackNumber: "RP123456789RU",
    status: "in_transit",
    total: 1750,
  },
  {
    id: "WOA-87102",
    createdAt: "2026-08-10T11:05:00.000Z",
    buyerId: "buyer-demo",
    sellerId: "seller-demo",
    items: [
      {
        productId: "handmade-candles",
        title: "Свечи соевые ручной работы, набор 3 шт",
        price: 890,
        qty: 5,
        image: CATALOG_IMAGE,
      },
    ],
    city: "Санкт-Петербург",
    address: "Невский пр., 28",
    delivery: "cdek",
    deliveryPrice: 390,
    eta: "доставлено",
    trackNumber: "CDEK-WOA-87102",
    status: "delivered",
    total: 4840,
  },
];

export const seedMessages: ChatMessage[] = [
  {
    id: "m-seed-1",
    sellerId: "seller-demo",
    buyerId: "buyer-demo",
    fromId: "buyer-demo",
    text: "Здравствуйте! Набор свечей ещё в наличии? Нужен к субботе.",
    createdAt: "16.08.2026, 10:14",
    read: true,
  },
  {
    id: "m-seed-2",
    sellerId: "seller-demo",
    buyerId: "buyer-demo",
    fromId: "seller-demo",
    text: "Да, ваниль и сандал есть. Могу отправить сегодня СДЭКом.",
    createdAt: "16.08.2026, 10:22",
    read: false,
  },
];

export const demoUsers: User[] = [
  {
    id: "buyer-demo",
    name: "Мария Покупатель",
    email: "maria@woason.ru",
    phone: "+7 900 111-22-33",
    role: "buyer",
  },
  {
    id: "seller-demo",
    name: "Магасов",
    email: "shop@woason.ru",
    phone: "+7 900 444-55-66",
    role: "seller",
    seller: {
      id: "seller-demo",
      shopName: "Лавка Магасова",
      description: "Свечи, аксессуары и вещи, которые хочется дарить. Своё производство, розница и опт.",
      logo: "🕯️",
      city: "Москва",
      delivery: ["cdek", "pochta"],
      banner: CATALOG_IMAGE,
      phone: "+7 900 444-55-66",
      kind: "shop",
    },
  },
];

export const DEMO_PASSWORD = "123456";

export function getProduct(id: string) {
  return products.find((p) => p.id === id);
}

export function getReel(id: string) {
  return reels.find((r) => r.id === id);
}

export function searchProducts(query: string, list: Product[]) {
  const q = query.trim().toLowerCase();
  if (!q) return list;
  return list.filter((p) =>
    [p.title, p.description, p.sellerName, p.city, p.tags.join(" ")]
      .join(" ")
      .toLowerCase()
      .includes(q),
  );
}
